version: '3.9'
services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "5000:5000"
    depends_on:
      - auth-db
    env_file:
      - variables.env
    volumes:
      - .:/auth-service

  auth-db:
    image: postgres:latest
    container_name: auth-db
    env_file:
      - variables.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - variables.env
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
