name: Python CI Pipeline with Docker Deployment

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Set up Python environment
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Analysing the code with pylint
      run: |
          pylint ./app --fail-under=9
      
    - name: Run Tests and Calculate Coverage
      run: |
        export FLASK_ENV=testing
        pip install pytest pytest-cov
        pytest -c pytest.ini --cov --cov-fail-under=85
      env:
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        MAIL_DEFAULT_SENDER: ${{ secrets.MAIL_DEFAULT_SENDER }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        REFRESH_SECRET_KEY: ${{ secrets.REFRESH_SECRET_KEY }}

    - name: Build and push the Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: munuhee/auth-service
        tags: v1, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
