name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Set up Python environment
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Initialize database
      run: |
        flask db init
        flask db migrate
        flask db upgrade
      env:
        FLASK_ENV: ${{ secrets.FLASK_ENV }}

    - name: Run pylint
      run: |
        pip install pylint
        pylint ./app --fail-under=10 || echo "Pylint check failed, please review your code."
      
    - name: Run Tests and Calculate Coverage
      run: |
        pip install pytest pytest-cov
        pytest -c pytest.ini --cov --cov-fail-under=85
      env:
        FLASK_ENV: ${{ secrets.FLASK_ENV }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        MAIL_DEFAULT_SENDER: ${{ secrets.MAIL_DEFAULT_SENDER }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        REFRESH_SECRET_KEY: ${{ secrets.REFRESH_SECRET_KEY }}
