on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Set up Python environment
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "export FLASK_ENV=testing" >> $GITHUB_ENV

    - name: Initialize SQLite Database
      run: |
        export FLASK_APP=run.py
        flask db init
        flask db migrate
        flask db upgrade

    - name: Run Unit Tests
      run: |
        export FLASK_ENV=testing
        python -m unittest discover
