name: Flask Application Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Set environment variable for testing
      run: |
        export FLASK_ENV=testing
      shell: bash

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
      env:
        FLASK_ENV: testing

    - name: Set up and initialize SQLite (for testing with an in-memory database)
      run: |
        export FLASK_ENV=testing
        python3 -c 'from app import app, db; app.app_context().push(); db.create_all()'

    - name: Run tests
      run: |
        python3 -m unittest discover -s app/tests

    - name: Clean up SQLite
      run: |
        python3 -c 'from app import db; db.drop_all()'

    - name: Remove the test database file
      run: |
        rm test.db  # Assuming 'test.db' is the SQLite test database file
