name: Flask Application Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python3 -m unittest discover -s app/tests

    - name: Clean up SQLite
      run: |
        python3 -c 'from app import db; db.drop_all()'

    - name: Set up and initialize SQLite (for testing with an in-memory database)
      run: |
        python3 -c 'from app import db; db.create_all()'

    - name: Start Flask application
      run: |
        python3 run.py
